### ISSUE TITLE
Flash fails.

### ISSUE THREAD

**Issue by MasterXX** [Chadster766/McWRT#103]
Whatever I do, I can't get your firmware to work.
I've installed the firmware (Flashed)
Router reboots, and the Power and eSATA lights come on.
When I try to go to the web interface, (192.168.200.1) I get a time out request.
After that, the router resets it self to the backed up firmware...
I'm lost... 
Flashing stock OpenWRT works.
Please help!

**Comment by Chadster766** [comment]
Do you have a version 1 WRT900AC?

**Comment by JW0914** [comment]
Have you verified the hash to make sure you're not flashing a corrupted download?  Another user on the OpenWRT WRT1900 thread a few days ago had a myriad of issues and the cause ended up being he had a corrupted download of the firmware.

**Comment by MasterXX** [comment]
@Chadster766 I've got the build in fan, so it's the V1. 
@JW0914 How do I check the hash? I see the hash of the copy I downloaded, but where is the original hash to compare it to?

**Comment by MasterXX** [comment]
@JW0914 
The hash from the latest file is:
42F28819FB972D5F90F34F7BA804BA33.

**Comment by MasterXX** [comment]
Also, this is the only firmware that wouldn't flash.
I've could flash OpenWRT Stock, and Kaloz's build with no problem.
The weird thing is, I have flashed your firmware before.
It worked then. I've reverted to stock, because first I didn't like it.
Now I want to give your firmware a second try, because it is overloaded with features in comparison with the stock OpenWRT firmware.

**Comment by JW0914** [comment]
You can install all the components of McWRT on OpenWRT.  This isn't to say don't use McWRT, simply that both can configured with the same packages

**Comment by MasterXX** [comment]
@JW0914 But how? It would be a pain in the ass to do that manually.
I also don't know how to prepare a auto install script.

**Comment by MasterXX** [comment]
I've got it fixed!! :D I'm a happy McWRT user now.
Solved by flashing the AAv1.0.8 build,
and then flashing the latest build.
