### ISSUE TITLE
[NOT A ISSUE] Owncloud Implementation request.

### ISSUE THREAD

**Issue by MasterXX** [Chadster766/McWRT#104]
Can you maybe pre install Owncloud as default? Not enabled, but installed? I have tryed to install it, but I've failed.
Or Transmission (Torrent downloader) Just like the ASUSWRT Firmware, who comes stock with Transmission installed.

Regards,
Damian.

**Comment by Chadster766** [comment]
If there is no security vulnerability or performance drop then add the packages to you "make menuconfig" and make another pull request.

Default configurations for the packages to be included in the image can be place in:
package/base-files/files/etc/

or

target/linux/armadaxp/base-files
