### ISSUE TITLE
Slow network transfer speeds

### ISSUE THREAD

**Issue by Tez-187** [Chadster766/McWRT#107]
The network transfer speeds are 10x slower than linksys OEM firmware. Just putting it out there so people know

**Comment by MasterXX** [comment]
Chad is already aware of this. It is caused by the driver.

**Comment by Tez-187** [comment]
Correct i just put this here so everyone can be aware

**Comment by Chadster766** [comment]
In release V2.4 I've updated the USB3 controller driver. Maybe it will make a difference with this issue.

**Comment by Tez-187** [comment]
Great i will test when home and let you know

**Comment by Tez-187** [comment]
Speeds are still very slow 13 MB/s after version 2.4 update so no gain in performance

**Comment by Chadster766** [comment]
Is the drive formatted ntfs and is that the upload or download speed? Is it married over wireless or word?

**Comment by Tez-187** [comment]
Yes drive is ntfs and speeds are wired. Transferring from pc to network USB 3.0 drive speeds are 13MB/s and from network drive back to pc is 54 MB/s. Linksys firmware was 70-80MB/s from pc to network drive

**Comment by Chadster766** [comment]
Those are the same speeds i see as well.

**Comment by Tez-187** [comment]
So is it possible to get the speeds up to linksys standards?

**Comment by Chadster766** [comment]
Sure but more work well need to be done. 


Regards,
 
Chad McCuewww.mccuesoft.com
www.protechs-online.com
IT Administrator\Database Administrator\Software and Website Developer
Electrical Class “M” Voice-Video-Data Technician
PLC\Electrical Control Applications Developer
Satellite\Home Theatre TechnicianOffice: 204-364-2096
Cell: 431-283-3021 Sent from my Samsung Galaxy smartphone.

-------- Original message --------
