### ISSUE TITLE
WRT1900 / WRT3200 USB to TTL converter logic level

### ISSUE THREAD

**Issue by silelis** [Chadster766/McWRT#108]
Hello,

Can You add to this tutorial:

https://github.com/Chadster766/McWRT/wiki/Linksys-WRT1900AC-Serial-Port

RX/ TX TTL levels? Is it +5V0 or +3V3? Very importnant to avoid serial port burning.

**Comment by nitroshift** [comment]
That's not my repo. Ask Chadster766.
