### ISSUE TITLE
Bricked WRT1900AC

### ISSUE THREAD

**Issue by cgcarlos** [Chadster766/McWRT#111]
Tried the Bootloader recovery as recommended and still fails to boot correctly. I have attached a txt file that shows when the router boots and fails. Is this router done and nothing can help it. When you power on the router you get a constant power led and the sata led is constanly on. Can't access network ports. Let me know if this router is a paper weight.

[WRT1900AC (Bricked).txt](https://github.com/Chadster766/McWRT/files/2498691/WRT1900AC.Bricked.txt)

**Comment by Chadster766** [comment]
Try the new instructions and u-boot images in the below wiki:

https://github.com/Chadster766/McDebian/wiki/C.-U%E2%80%90Boot-Recovery

**Comment by rip057** [comment]
Your need to get a uart ttl USB cable 4 pin... They cost about 3 dollars
and take apart the router hook up the pins to the cable via the guide and
pray you don't really go wtf at this level cause it gets super hairy....
