### ISSUE TITLE
Wiki is missing photos

### ISSUE THREAD

**Issue by crass** [Chadster766/McWRT#114]
The photos in the [serial port howto](https://github.com/Chadster766/McWRT/wiki/Linksys-WRT1900AC-Serial-Port) are being loaded from http://www.gypsy-designs.com which is not serving them (getting a connection reset when trying to fetch). Can you [embed the photos](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2) in the wiki instead of hosting them on some random site?

**Comment by Chadster766** [comment]
That wiki was created by @gufus. 

You could ask him if he can provide the pics.
