### ISSUE TITLE
swconfig doesn't work

### ISSUE THREAD

**Issue by Chadster766** [Chadster766/McWRT#20]
swconfig

**Comment by mmilburn** [comment]
Kaloz has added the dts changes: https://dev.openwrt.org/changeset/43854/

**Comment by Chadster766** [comment]
Nice, does that help with your switch driver or is that no longer needed.

**Comment by mmilburn** [comment]
CC already has @leitec's original mvsw6171 driver.  The only thing left is to test his patches for 802.1q vlans.

**Comment by mmilburn** [comment]
Because it's taken me a while to get to this, I had to make a few trivial changes to the first patch:
```
(20:51:%) diff 0001-mvsw6171-rename-to-mvsw61xx.patch 0001-mvsw6171-rename-to-mvsw61xx.patch.new                                                                                               (2015/01/07)
2305c2305
< - obj-$(CONFIG_AR8216_PHY)	+= ar8216.o
---
> - obj-$(CONFIG_AR8216_PHY)	+= ar8216.o ar8327.o
2334c2334
< + obj-$(CONFIG_AR8216_PHY)	+= ar8216.o
---
> + obj-$(CONFIG_AR8216_PHY)	+= ar8216.o ar8327.o
2363c2363
< - obj-$(CONFIG_AR8216_PHY)	+= ar8216.o
---
> - obj-$(CONFIG_AR8216_PHY)	+= ar8216.o ar8327.o
2392c2392
< + obj-$(CONFIG_AR8216_PHY)	+= ar8216.o
---
> + obj-$(CONFIG_AR8216_PHY)	+= ar8216.o ar8327.o
```

after that everything applies cleanly.  After I finish building an image, my plan for testing is as follows:
1.  Make sure I can query and change individual port state with swconfig
2.  Setup a dummy VLAN and ```tcpdump -e -i``` to confirm tagged frames.

Since I am not an expert on this, please let me know if you have a better way to test this.  Or, if you think I am testing incorrectly.

**Comment by Chadster766** [comment]
If this is your driver mod than I will do VLAN testing with my equipment too.

**Comment by leitec** [comment]
Thanks for testing. I will refresh the first patch when I submit it.

Your testing procedure sounds good to me. Here's an excerpt from my config using a '6171 switch. I have tagged packets coming in and out from switch port 4 (WAN, on my hardware) and going tagged into port 6 (eth0 on my hardware) plus untagged on two of the LAN ports.

```
config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '11'
        option ports '0 1 4t 6t'
```

There's also a corresponding config for `eth0.11` There's a further option, `option vid` under `switch_vlan` that sets the actual transmitted VID. It defaults to whatever `vlan` is set to, but in the case you want a VID > 64, you can set `option vid '300'` or whatever for `eth0.300`.

**Comment by mmilburn** [comment]
Did a simple test, tagging appears:
```
config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '4 6t'
```
```
tcpdump -eni eth1
...
03:25:02.315780 10:7b:ef:98:af:a4 > 01:00:5e:7f:ff:fa, ethertype 802.1Q (0x8100), length 406: vlan 1, p 0, ethertype IPv4, 192.168.0.1.1900 > 239.255.255.250.1900: UDP, length 360
```

**Comment by mmilburn** [comment]
I was also able to set qmode and pvid with swconfig.

**Comment by mmilburn** [comment]
@leitec, let me know if I need to do more in depth testing.  Things appear to work fine.

**Comment by leitec** [comment]
I think that's it. Thanks a lot for testing!

**Comment by mmilburn** [comment]
No problem.  Thanks for all the help Claudio.

@Chadster766 I will close this ticket once Claudio's patches appear in trunk.

**Comment by mmilburn** [comment]
https://patchwork.ozlabs.org/patch/427286/

**Comment by mmilburn** [comment]
Changes applied to trunk.  This is in CC now.

Hi Mark,

On Fri, Jan 09, 2015 at 04:21:10PM -0700, Mark Milburn wrote:
> Use Claudio's renamed mvsw6171 driver.
> Depends upon https://patchwork.ozlabs.org/patch/427183/ patchset.
> 
> Signed-off-by: Mark Milburn <mark.a.milburn@gmail.com>
> ---
>  target/linux/mvebu/config-3.14 | 2 +-
>  target/linux/mvebu/config-3.18 | 2 +-
>  2 files changed, 2 insertions(+), 2 deletions(-)

Applied as a part of r43938. Thank you!

Luka
