### ISSUE TITLE
luci-ssl install error dependency libustream-polarssl

### ISSUE THREAD

**Issue by Chadster766** [Chadster766/McWRT#33]
We need to find a patch or the package libustream-polarssl

**Comment by pavgup** [comment]
It's totally within reason that I'm wrong, but I just flashed the latest (june 9) trunk of CC and I'm running into this error again.  At the risk of embarrassing myself (I swear, I've tried to read the docs), I flashed the latest stuff and after opkg updating, I'm being asked for the libustream-polarssl dependency which doesn't seem to be available.

**Comment by Chadster766** [comment]
I haven't look into this on CC but I would think you can install the package via:

opkg update
opkg install luci

**Comment by pavgup** [comment]
Yep and this looks like a temporary broken package that will eventually find it's way.  For the moment, you can manually install a slightly older variant out of the CC RC:  

`opkg install http://downloads.openwrt.org/chaos_calmer/15.05-rc1/mvebu/generic/packages/base/libustream-polarssl_2015-04-14-a4ca61527236e89eb9efb782f
d9bfd04796144e3_mvebu.ipk`

**Comment by Chadster766** [comment]
Thanks for the update.
