### ISSUE TITLE
LED issues

### ISSUE THREAD

**Issue by nitroshift** [Chadster766/McWRT#4]
E-sata LED stays ON, even though nothing is plugged in the e-sata port and the WPS keeps blinking at all times. Also, WAN MAC address stays set at 00:00:00:00:00.

**Comment by Chadster766** [comment]
I'm going to start working on this issue again.

**Comment by Tez-187** [comment]
Thanks for reopening this issue keep up the good work

**Comment by ppseprus** [comment]
Hey All!

Although this one is closed, I have not found any other place to report these...
If you could refer me to some other thread, I'd really appreciate that!

I have a relatively new Linksys wrt1900ACS and

#### 1) the power, WAN, 2.5GHz and 5GHz white LEDs are all dimmed like you talked above

Running OpenWRT, I can set the LED to simply stay on, and with the following command, I can verify that brightness is at its brightest

```
vim /sys/class/leds/pca963x:shelby:white:wan/brightness
# 255
```

Using the `:amber` LED instead (where available), one can see that the brightness issue only affects the white ones.

#### 2) the triggers of some LEDs cannot be changed

##### a) Using LuCI, I'm trying to set different triggers for eg. the 2.5 and 5GHz LEDs. For example to simple stay on. But the LEDs default to their normal config and flicker instead.

##### b) Additionally, while there are no named LEDs for the 4 UTP ports, there are seven unnamed LEDs, which also cannot be turned on:

```
pca963x:0:68:10
pca963x:0:68:11
pca963x:0:68:12
pca963x:0:68:13
pca963x:0:68:14
pca963x:0:68:15
pca963x:0:68:4
```

Thank & regards,
Peter
