### ISSUE TITLE
usbnet support / kmod dependency errors

### ISSUE THREAD

**Issue by hh** [Chadster766/McWRT#78]
I'm trying to load  [usbnet](http://www.linux-usb.org/usbnet/) in order to [tether](http://wiki.openwrt.org/doc/howto/usb.tethering).

Part of that is loading [usb basic support](http://wiki.openwrt.org/doc/howto/usb.essentials) including kmod-usb2 and friends.

Here is the [AX8872](http://www.asix.com.tw/download.php?sub=driverdetail&PItemID=86) showing up, but without the kernel modules I'm out of luck.

```
root@OpenWrt:~# dmesg | tail -1
[40595.558276] usb 3-2: new high-speed USB device number 3 using etxhci_hcd_131007
root@OpenWrt:~# lsusb -d 0b95:7720
Bus 003 Device 003: ID 0b95:7720 ASIX Electronics Corp. AX88772
```

When I use the web interface ```/cgi-bin/luci/;stok=KEY/admin/system/packages?submit=1&install=kmod-usb2``` I get these errors.

```
Installing kmod-usb2 (3.2.36-1) to root...
Downloading http://www.protechs-online.com/downloads/McWRT/packages/kmod-usb2_3.2.36-1_armadaxp.ipk.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb2:
 * 	kernel (= 3.2.36-1-51098ce98ff1bc265ed1fe337696946b) * 
 * opkg_install_cmd: Cannot install package kmod-usb2.
```

**Comment by hh** [comment]
@Chadster766 did kmod-usb-net make it in to latest release?

**Comment by Chadster766** [comment]
Yes
