### ISSUE TITLE
security: update ntp packages to 4.2.8 release

### ISSUE THREAD

**Issue by DavidMcWRT** [Chadster766/McWRT#81]
current ntpd and ntp-utils packages are 4.2.6p5.

An updated version of ntp has been released, 4.2.8, containing security updates.

Please update ntpd and ntp-utils to the newer version.

**Comment by OperatorOverload** [comment]
Given the "on the cusp" support in trunk, I'm not going to do another AA build, just don't think it makes any sense to spend the time to rebuild everything (packages, etc).  Leaving the issue open for now though until CC builds are fully functional

**Comment by DavidMcWRT** [comment]
Funnily enough I've literally just flashed lifehacksback's trunk build and can confirm the ntp package is the newest 4.2.8 release.

No ntp-utils package available tho :/

Guess we need to leave this open just to keep it as a warning for those running McWRT.

**Comment by Chadster766** [comment]
@DavidMcWRT 

Unless I'm mistaken the ntp vulnerabilities are regards a system running an ntp server and not the client. If a WRT1900AC owner decided to run an ntp server or if it is enabled by default then only users allowed to connect to the router's wlan or lan would be able to cause the DOS attack.

Hardly a concern IMO.
