### ISSUE TITLE
Add MIA (Moms internet Access helper) as package for OpenWRT

### ISSUE THREAD

**Issue by raversnet** [Chadster766/McWRT#84]
Not sure if this is the place to ask but since i use this firmware and love it.... :)

I would like to request this package compiled for OpenWRT.  Its a parent scheduling module so i can set blocks for my teenager.  Unfortunately i dont have the platform to compile.  Would love if someone could tackle this and add to the repository.  The author gave me the code to work with.  

If not then thats cool too.  Thanks anyways :)

Code:
https://drive.google.com/folderview?id=0BwhvHRyRV5PlYkp2YlJ6Y3M5Ync&usp=sharing

MIA website: 
http://www.avidz.net/mia/

**Comment by Chadster766** [comment]
I will look into it.

**Comment by rip057** [comment]
Good luck... also I already have gawk sed and etc for cc compiled and
working beautifully

**Comment by 7LK** [comment]
great idea
