### ISSUE TITLE
Hurricane Electric Tunnelbroker IPv6 Setup

### ISSUE THREAD

**Issue by jfargen** [Chadster766/McWRT#89]
Chad,

I followed along with your directions to setup an interface for HE.net Tunnelbroker IPv6 service. After following the directions and restarting the restart I get an error. Mind checking it out in the attached screenshot?

Regards,
Jamie
![screen shot 2015-02-16 at 6 02 52 pm](https://cloud.githubusercontent.com/assets/4099966/6220588/18733a7e-b606-11e4-901e-bbff79caa44d.png)

**Comment by Chadster766** [comment]
Hi :smile: 

Are you running the v1.0.8 firmware?

**Comment by gufus** [comment]
Hi,

 

Nope, stock right now

 

gufus
