### ISSUE TITLE
Add DNScrypt-proxy package

### ISSUE THREAD

**Issue by AliceGrey** [Chadster766/McWRT#90]
I would really love to have dnscrypt on the wrt. It's a really popular package to use.

**Comment by Chadster766** [comment]
Did you try to compile it? If you need help I can advise.

**Comment by AliceGrey** [comment]
Compile dnscrypt? Or McWrt?

**Comment by Chadster766** [comment]
You can compile both or just the package.

http://wiki.openwrt.org/doc/howtobuild/single.package

**Comment by AliceGrey** [comment]
Which architecture is the wrt?

**Comment by Chadster766** [comment]
If you clone the McWRT repo and run "update.sh" and then "make menuconfig"; the arch will be listed and selected.

You can build OpenWRT on x32 or x64 Linux system.

**Comment by AliceGrey** [comment]
I meant out of these architectures. http://downloads.openwrt.org/attitude_adjustment/12.09/ Which one do I build dnscrypt for?

**Comment by Chadster766** [comment]
It's not in that list.

There are two options:
AA = armadaxp
BB\CC = mvebu

**Comment by Chadster766** [comment]
To build this package for the McWRT firmware. You clone this repo. Then you can add the package source and in "make menuconfig" add the package to the build. You will most likely have to troubleshoot compile errors and find or make patches.
