### ISSUE TITLE
Possibly a stupid question... but does this work for EA6900? or just WRT1900AC?

### ISSUE THREAD

**Issue by joshuairl** [Chadster766/McWRT#96]

**Comment by Chadster766** [comment]
Just the WRT1900AC

**Comment by joshuairl** [comment]
No way to run OpenWRT on EA6900 that you know of?

**Comment by joshuairl** [comment]
Thanks for quick response too!

**Comment by Chadster766** [comment]
Sorry I not AFAIK but I've heard of DD-WRT being loaded on the EA6900. I recommend you post in the OpenWRT forum because during development I thought I saw support being explorered for other EA series routers.

**Comment by alirz1** [comment]
I have used DD wet on the 6900 about 4 months ago. It is supported by ddwrt

**Comment by joshuairl** [comment]
I've tried various builds close to a year ago and weren't stable but maybe it's improved

**Comment by Chadster766** [comment]
Finally someone that confirms it's possible for DD-WRT on the EA6900. I would be curious on how the newer version of DD-WRT work on the EA6900 since I have one of those as well. I find the EA6900 very fast wired and wireless. The new Linksys firmware for the EA6900 is good too.

**Comment by joshuairl** [comment]
I personally hate how simple the smart wifi UI is and it feels very limited.

**Comment by Chadster766** [comment]
Yes compared to OpenWRT and DD-WRT the Linksys firmware doesn't have nearly the same amount of features.

For those with basic network needs than the Linksys firmware is a very good option.

**Comment by alirz1** [comment]
My Primary reason for using dd-wrt or openwrt is the fact that it lets me use Wake on WAN using broadcast Ips on the LAN. Linksys oem firmwares dont allow that..But i also have other scripts and 3rd party apps running on my router now thanks to these open firmwares.
I had been using dd-wrt on various routers for the past 6 or so years.
Only jumped on the openwrt wagon 3 months ago when i got the WRT1900AC..Used Chadster build  uptil last week without any issues till i found an issue with the WAN interface restarting at lease renew time....Decided to try the lastest CC builds and so far they have been good.

**Comment by Koulio** [comment]
http://www.linksysinfo.org/index.php?threads/asuswrt-merlin-tomato-shibby-or-toastman-dd-wrt-on-linksys-ea6900.71718/

**Comment by Chadster766** [comment]
Sorry McWRT is only compatible with the WRT1900AC V1.

I've heard of DD-WRT running on the EA6900 but it doesn't seem to be officially supported.

**Comment by kyshop38** [comment]
Try ea6900 merlin

**Comment by rip057** [comment]
Nice Necro.  It brings me back :)
