### ISSUE TITLE
WRT1200ac Support?

### ISSUE THREAD

**Issue by SuperSpyTX** [Chadster766/McWRT#97]
I'm getting the sense that while it uses marvell's chipset, McWRT is only for the Linksys WRT1900ac and not for the newer WRT1200ac.

Right?

**Comment by Chadster766** [comment]
Currently McWRT only support the WRT1900AC V1

**Comment by Chadster766** [comment]
If you have the knowledge you could and the support for it and publish a pull request for the McWRT repo

**Comment by SuperSpyTX** [comment]
If I only had the time :(

Thanks anyways! Just making sure.
